# ~/.config/alacritty/alacritty.toml

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

[window]
opacity = 1
padding = { x = 2, y = 0 }
decorations = "None"

[font]
size = 12.0
builtin_box_drawing = true

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.15
blink_interval = 500

[scrolling]
history = 10000
multiplier = 3 

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]
